# Copyright (c) 2026 Huawei Technologies Co., Ltd. All rights reserved.
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

show_help() {
    cat << EOF
torchtitan-npu build script
sh build.sh [options]

Build:
    -b, --build                       Build whl package
    -c, --clean                       Clean build artifacts
    -i, --install                     Perform developer installation

Test:
    -u, --ut                          Run all unit tests
    -s, --smoke                       Run smoke validation (core + extended by default)

Report:
    --generate-report                 Generate HTML test report

Examples:
    sh build.sh -a                    # Run build, all UT, and all smoke tests
    sh build.sh -f pr_list.txt -u     # Incremental unit tests
    sh build.sh -u --generate-report  # Run all UT and generate report
    sh build.sh -s --generate-report  # Run full smoke validation and generate report
    ONLY_CORE_SMOKE=true sh build.sh -s
    ONLY_EXTENDED_SMOKE=true sh build.sh -s
    ONLY_UPSTREAM_SMOKE=true sh build.sh -s
EOF
    exit 0
}

set -e

# Global variable
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="${SCRIPT_DIR}"
OUTPUT_DIR="${PROJECT_ROOT}/output"
REPORT_DIR="${PROJECT_ROOT}/test_reports"
TITAN_VERSION="v0.2.1"
TITAN_DIR="${PROJECT_ROOT}/third_party/torchtitan"

# Default configuration
NGPU=2
SMOKE_STEP=10
SMOKE_CONFIG="${PROJECT_ROOT}/tests/smoke_tests/smoke_test.toml"
TIMEOUT_SECONDS=${TIMEOUT_SECONDS:-300}
ONLY_CORE_SMOKE=${ONLY_CORE_SMOKE:-false}
ONLY_EXTENDED_SMOKE=${ONLY_EXTENDED_SMOKE:-false}
ONLY_UPSTREAM_SMOKE=${ONLY_UPSTREAM_SMOKE:-false}
RUN_TORCHTITAN_UT=${RUN_TORCHTITAN_UT:-true}
UPSTREAM_TEST_SUITE=${UPSTREAM_TEST_SUITE:-features}
UPSTREAM_TEST_NAME=${UPSTREAM_TEST_NAME:-all}

# Colors and logging
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

build_pytest_report_args() {
    local report_name="$1"
    local args="--junitxml=${REPORT_DIR}/${report_name}.xml"

    if [[ "$DO_GENERATE_REPORT" == "true" ]]; then
        args="$args --html=${REPORT_DIR}/${report_name}.html --self-contained-html"
    fi

    echo "$args"
}

write_report_index() {
    local index_file="${REPORT_DIR}/README.md"

    mkdir -p "$REPORT_DIR"
    cat > "$index_file" << EOF
# Test Reports

Generated by \`build.sh\`.

## Available Artifacts

EOF

    local artifact
    for artifact in "$REPORT_DIR"/*.xml "$REPORT_DIR"/*.html "$REPORT_DIR"/*.log; do
        if [[ -f "$artifact" ]]; then
            printf -- "- %s\n" "$(basename "$artifact")" >> "$index_file"
        fi
    done

    log_info "Report index updated: ${index_file}"
}

# Python 3.10 paths
PYTHON310_INSTALL_DIR="/usr/local/python3.10.18"
PYTHON310_LINK_DIR="/usr/local/python/python310"

detect_pkg_manager() {
    if command -v apt-get >/dev/null 2>&1; then
        echo "apt"
    elif command -v yum >/dev/null 2>&1; then
        echo "yum"
    elif command -v dnf >/dev/null 2>&1; then
        echo "dnf"
    else
        return 1
    fi
}

install_python_build_deps() {
    local pkg_manager
    pkg_manager=$(detect_pkg_manager) || {
        log_error "Unsupported package manager. Please install Python build dependencies manually."
        return 1
    }

    case "$pkg_manager" in
        apt)
            apt-get update
            apt-get install -y \
                build-essential wget libbz2-dev liblzma-dev libsqlite3-dev \
                libffi-dev libreadline-dev libncurses5-dev zlib1g-dev libssl-dev
            ;;
        yum)
            yum install -y \
                gcc gcc-c++ make wget bzip2-devel xz-devel sqlite-devel \
                libffi-devel readline-devel ncurses-devel zlib-devel openssl-devel
            ;;
        dnf)
            dnf install -y \
                gcc gcc-c++ make wget bzip2-devel xz-devel sqlite-devel \
                libffi-devel readline-devel ncurses-devel zlib-devel openssl-devel
            ;;
    esac
}

# Setup Python 3.10 environment
setup_python310() {
    local python_bin_dir="${PYTHON310_LINK_DIR}/bin"

    # Check if python3.10 exists and has required modules
    local need_install=false
    if [[ ! -x "${python_bin_dir}/python3" ]]; then
        log_info "Python 3.10 not found at ${python_bin_dir}"
        need_install=true
    elif ! "${python_bin_dir}/python3" -c "import sqlite3, bz2, lzma" 2>/dev/null; then
        log_info "Python 3.10 missing required modules (sqlite3, bz2, lzma)"
        need_install=true
    fi

    # Install Python 3.10 if needed
    if [[ "$need_install" == "true" ]]; then
        log_info "Installing Python 3.10..."

        echo "  Installing build dependencies "
        install_python_build_deps

        echo "  Downloading Python 3.10 source "
        cd /tmp
        wget --no-check-certificate https://www.python.org/ftp/python/3.10.18/Python-3.10.18.tgz
        tar -xzf Python-3.10.18.tgz
        cd Python-3.10.18

        echo "  Compiling and installing "
        ./configure --prefix="$PYTHON310_INSTALL_DIR"
        make -j$(nproc)
        make install

        echo "  Creating symbolic links "
        rm -rf "$PYTHON310_LINK_DIR"
        ln -sf "$PYTHON310_INSTALL_DIR" "$PYTHON310_LINK_DIR"

        echo "  Verifying "
        "${python_bin_dir}/python3" -c "import sqlite3, bz2, lzma; print('Modules complete: ok')"
        "${python_bin_dir}/python3" --version

        cd "$PROJECT_ROOT"
    fi

    # Create symlinks for python/pip (if python3/pip3 exist but python/pip don't)
    ln -sf "${python_bin_dir}/python3" "${python_bin_dir}/python" 2>/dev/null || true
    ln -sf "${python_bin_dir}/pip3" "${python_bin_dir}/pip" 2>/dev/null || true

    # Add Python bin dir to PATH with highest priority
    export PATH="${python_bin_dir}:$PATH"

    log_info "Python 3.10 ready: $(which python)"
}

# Setup Python 3.10 environment
setup_python310

# Operation sign
DO_BUILD=false
DO_UNIT_TEST=false
DO_SMOKE_TEST=false
DO_CLEAN=false
DO_INSTALL=false
PR_FILELIST=""

# Report flag
DO_GENERATE_REPORT=false

parse_args() {
    if [[ $# -eq 0 ]]; then
        DO_BUILD=true
        return
    fi

    while [[ $# -gt 0 ]]; do
        case $1 in
            -b|--build)
                DO_BUILD=true
                shift
                ;;
            -c|--clean)
                DO_CLEAN=true
                shift
                ;;
            -i|--install)
                DO_INSTALL=true
                shift
                ;;
            -u|--ut)
                DO_UNIT_TEST=true
                shift
                ;;
            -s|--smoke)
                DO_SMOKE_TEST=true
                shift
                ;;
            -a|--all)
                DO_BUILD=true
                DO_UNIT_TEST=true
                DO_SMOKE_TEST=true
                shift
                ;;
            -f|--filelist)
                PR_FILELIST="$2"
                shift 2
                shift
                ;;
            # Report option
            --generate-report)
                DO_GENERATE_REPORT=true
                shift
                ;;
            -h|--help)
                show_help
                ;;
            *)
                log_error "Unknown param: $1"
                exit 1
                ;;
        esac
    done
}


# Environment Inspection
check_python_env() {
    log_info "Checking Python..."
    if ! command -v python3 &> /dev/null; then
        log_error "Python3 not installed"
        exit 1
    fi
}

check_dependencies() {
    log_info "Checking dependencies..."

    python3 -m pip install --upgrade pip

    # Uninstall triton before installing triton_ascend (they conflict)
    if python3 -c "import triton" 2>/dev/null; then
        log_info "Uninstalling triton (conflicts with triton_ascend)..."
        python3 -m pip uninstall -y triton
    fi

    # Use CI-specific requirements if available, otherwise use default
    local req_file="${PROJECT_ROOT}/requirements_ci.txt"
    if [[ ! -f "$req_file" ]]; then
        req_file="${PROJECT_ROOT}/requirements.txt"
    fi

    if [[ -f "$req_file" ]]; then
        log_info "Installing dependencies from $(basename $req_file)..."
        python3 -m pip install -r "$req_file" | grep -v "Requirement already satisfied"
    fi
    python3 -m pip list
}

check_environment() {
    check_python_env
    check_dependencies
}

# do_clean
do_clean() {
    cd "$PROJECT_ROOT"

    rm -rf build/ dist/ *.egg-info/ output/
    rm -rf .pytest_cache/ .coverage htmlcov/
    rm -rf test_reports/

    find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    find . -type f -name "*.pyc" -delete 2>/dev/null || true

    log_info "Cleaning complete"
}

# do_build
do_build() {
    log_info "Building whl"

    cd "$PROJECT_ROOT"
    mkdir -p "$OUTPUT_DIR"

    python -m pip install --quiet build wheel setuptools

    python -m build --wheel --outdir "$OUTPUT_DIR"

    if [[ $? -eq 0 ]]; then
        log_info "Build success!"
        ls -la "$OUTPUT_DIR"/*.whl 2>/dev/null || log_error "WHL file not found"
    else
        log_error "Build failure!"
        exit 1
    fi
}

# Development mode install
do_install() {
    log_info "Development Mode Installation"

    cd "$PROJECT_ROOT"
    python3 -m pip install -e .

    log_info "Installation success!"
}

# Run torchtitan upstream unit tests (with NPU patches applied)
run_torchtitan_tests() {
    log_info "Running torchtitan upstream unit tests..."

    mkdir -p "$REPORT_DIR"

    # Ensure torchtitan_npu is installed (applies patches on import)
    if ! python3 -c "import torchtitan_npu" 2>/dev/null; then
        python3 -m pip install -e .
    fi

    # Clone torchtitan source if not exists
    if [ ! -d "$TITAN_DIR" ]; then
        log_info "Cloning torchtitan source..."
        mkdir -p third_party
        git clone --branch $TITAN_VERSION --depth 1 \
            https://gitcode.com/GitHub_Trending/to/torchtitan.git $TITAN_DIR
    fi

    # Create conftest.py in torchtitan test dir to ensure import torchtitan_npu before each test
    local titan_test_dir="${TITAN_DIR}/tests/unit_tests"
    local conftest_file="${titan_test_dir}/conftest.py"

    if [[ ! -d "$titan_test_dir" ]]; then
        log_error "Torchtitan unit test directory not found: $titan_test_dir"
        return 1
    fi
    cat > "$conftest_file" << 'EOF'
# Auto-generated conftest for torchtitan-npu patch testing
import pytest

def pytest_configure(config):
    """Import torchtitan_npu to apply NPU patches before running tests."""
    import torchtitan_npu  # noqa: F401
EOF

    # Save original PYTHONPATH and set torchtitan source path
    local saved_pythonpath="$PYTHONPATH"
    export PYTHONPATH="${TITAN_DIR}:${PROJECT_ROOT}:${PYTHONPATH}"

    local pytest_args="-v --tb=short --import-mode=importlib"
    pytest_args="$pytest_args $(build_pytest_report_args "torchtitan_ut_report")"

    # Ignore tests incompatible with NPU environment (ut runs off-device)
    pytest_args="$pytest_args --ignore=tests/unit_tests/test_tokenizer.py"
    pytest_args="$pytest_args --ignore=tests/unit_tests/test_activation_checkpoint.py"
    pytest_args="$pytest_args --ignore=tests/unit_tests/test_download_hf_assets.py"

    # Test target: torchtitan upstream unit tests
    local test_target="tests/unit_tests/"

    # Switch to torchtitan directory (tests use relative paths like ./torchtitan/models/...)
    cd "${TITAN_DIR}"
    log_info "Running torchtitan tests from: $(pwd)"
    set +e
    python3 -m pytest $pytest_args $test_target
    local exit_code=$?
    set -e

    # Return to project root
    cd "$PROJECT_ROOT"

    # Cleanup: remove the generated conftest file
    rm -f "$conftest_file"

    # Restore PYTHONPATH
    export PYTHONPATH="$saved_pythonpath"

    if [[ $exit_code -eq 0 ]]; then
        log_info "Torchtitan upstream tests passed!"
    elif [[ $exit_code -eq 5 ]]; then
        log_info "No torchtitan tests found to run."
    else
        log_error "Torchtitan upstream tests failed (exit_code=$exit_code)"
        return $exit_code
    fi
}

# Run torchtitan-npu local unit tests
# Optional param: test_file_list (for incremental testing)
run_npu_tests() {
    log_info "Running torchtitan-npu local unit tests..."

    mkdir -p "$REPORT_DIR"

    # Ensure torchtitan_npu is installed
    if ! python3 -c "import torchtitan_npu" 2>/dev/null; then
        python3 -m pip install -e .
    fi

    local pytest_args="-v --tb=short --confcutdir=tests --import-mode=importlib"
    pytest_args="$pytest_args $(build_pytest_report_args "npu_ut_report")"
    pytest_args="$pytest_args --cov=torchtitan_npu --cov-report=html:${REPORT_DIR}/coverage"
    pytest_args="$pytest_args --cov-report=term-missing"

    # Test target: local npu unit tests
    local test_target="tests/unit_tests/"

    # Support incremental testing via PR_FILELIST
    if [[ -n "$PR_FILELIST" && -f "$PR_FILELIST" ]]; then
        log_info "Filtering tests based on PR list..."
        local filtered_tests=$(get_affected_tests "$PR_FILELIST")
        if [[ -n "$filtered_tests" ]]; then
            test_target="$filtered_tests"
        else
            log_info "No relevant local test cases to run based on PR list."
            return 0
        fi
    fi

    if [[ ! -d "tests/unit_tests" ]]; then
        log_error "Local unit_tests directory not found"
        return 1
    fi

    log_info "Running NPU tests from: $test_target"
    set +e
    python3 -m pytest $pytest_args $test_target
    local exit_code=$?
    set -e

    if [[ $exit_code -eq 0 ]]; then
        log_info "Torchtitan-npu local tests passed!"
    elif [[ $exit_code -eq 5 ]]; then
        log_info "No local tests found to run."
    else
        log_error "Torchtitan-npu local tests failed (exit_code=$exit_code)"
        return $exit_code
    fi
}

# Run function-level UT (fake tensor tests)
run_function_ut() {
    log_info "Running function-level UT (fake tensor tests)..."
    mkdir -p "$REPORT_DIR"

    local pytest_args="-v --tb=short --confcutdir=tests --import-mode=importlib"
    pytest_args="$pytest_args $(build_pytest_report_args "ut_functions_report")"
    
    local test_target="tests/unit_tests/functions/"
    
    if [[ ! -d "$test_target" ]]; then
        log_info "Function-level test directory not found, skipping..."
        return 0
    fi

    log_info "Running function tests from: $test_target"
    set +e
    python3 -m pytest $pytest_args $test_target
    local exit_code=$?
    set -e

    if [[ $exit_code -eq 0 ]]; then
        log_info "Function-level UT passed!"
    elif [[ $exit_code -eq 5 ]]; then
        log_info "No function-level tests found."
    else
        log_error "Function-level UT failed (exit_code=$exit_code)"
        return $exit_code
    fi
}

# Run module-level UT
run_module_ut() {
    log_info "Running module-level UT..."
    mkdir -p "$REPORT_DIR"

    local pytest_args="-v --tb=short --confcutdir=tests --import-mode=importlib"
    pytest_args="$pytest_args $(build_pytest_report_args "ut_modules_report")"
    
    local test_target="tests/unit_tests/modules/"
    
    if [[ ! -d "$test_target" ]]; then
        log_info "Module-level test directory not found, skipping..."
        return 0
    fi

    log_info "Running module tests from: $test_target"
    set +e
    python3 -m pytest $pytest_args $test_target
    local exit_code=$?
    set -e

    if [[ $exit_code -eq 0 ]]; then
        log_info "Module-level UT passed!"
    elif [[ $exit_code -eq 5 ]]; then
        log_info "No module-level tests found."
    else
        log_error "Module-level UT failed (exit_code=$exit_code)"
        return $exit_code
    fi
}

# Run feature-level UT
run_feature_ut() {
    log_info "Running feature-level UT..."
    mkdir -p "$REPORT_DIR"

    local pytest_args="-v --tb=short --confcutdir=tests --import-mode=importlib"
    pytest_args="$pytest_args $(build_pytest_report_args "ut_features_report")"
    
    local test_target="tests/unit_tests/features/"
    
    if [[ ! -d "$test_target" ]]; then
        log_info "Feature-level test directory not found, skipping..."
        return 0
    fi

    log_info "Running feature tests from: $test_target"
    set +e
    python3 -m pytest $pytest_args $test_target
    local exit_code=$?
    set -e

    if [[ $exit_code -eq 0 ]]; then
        log_info "Feature-level UT passed!"
    elif [[ $exit_code -eq 5 ]]; then
        log_info "No feature-level tests found."
    else
        log_error "Feature-level UT failed (exit_code=$exit_code)"
        return $exit_code
    fi
}

# Unit test
do_unit_test() {
    log_info "Start unit tests..."

    cd "$PROJECT_ROOT"

    python3 -m pip install pytest pytest-html pytest-cov pytest-mock

    log_info "listing dependencies..."
    python3 -m pip list

    local overall_exit_code=0

    # Incremental test mode: only run local tests filtered by PR_FILELIST
    if [[ -n "$PR_FILELIST" && -f "$PR_FILELIST" ]]; then
        log_info "Incremental test mode enabled (PR_FILELIST: $PR_FILELIST)"
        run_npu_tests
        local npu_exit=$?
        if [[ $npu_exit -ne 0 && $npu_exit -ne 5 ]]; then
            log_error "Incremental tests failed!"
            exit 1
        fi
        log_info "Incremental tests completed!"
        return 0
    fi

    # Full test mode: run the configured UT phases.
    if [[ "$RUN_TORCHTITAN_UT" == "true" ]]; then
        run_torchtitan_tests
        local titan_exit=$?
        if [[ $titan_exit -ne 0 && $titan_exit -ne 5 ]]; then
            overall_exit_code=1
        fi
    else
        log_info "Skipping torchtitan upstream unit tests (RUN_TORCHTITAN_UT=${RUN_TORCHTITAN_UT})"
    fi

    run_npu_tests
    local npu_exit=$?
    if [[ $npu_exit -ne 0 && $npu_exit -ne 5 ]]; then
        overall_exit_code=1
    fi

    if [[ $overall_exit_code -eq 0 ]]; then
        write_report_index
        log_info "All unit tests passed!"
    else
        write_report_index
        log_error "Some unit tests failed!"
        exit 1
    fi
}

# only add increment tests
get_affected_tests() {
    local filelist="$1"
    local test_files=""

    while IFS= read -r changed_file || [[ -n "$changed_file" ]]; do
        [[ -z "$changed_file" || "$changed_file" == \#* ]] && continue

        if [[ "$changed_file" == torchtitan_npu/*.py ]]; then
            local module_name=$(basename "changed_file" .py)
            local test_file="tests/test_${module_name}.py"
            if [[ -f "$test_file" ]]; then
                test_files="$test_files $test_file"
            fi
        fi

        if [[ "$changed_file" == tests/*.py ]]; then
            if [[ -f "changed_file" ]]; then
                test_files="$test_files $test_file"
            fi
        fi
    done < "$filelist"

    echo "$test_files" | tr ' ' '\n' | sort -u | tr '\n' ' '
}

# Run upstream integration tests (torchtitan source with NPU patches)
# Mapping to upstream integration coverage:
# - S-044: model init / basic startup path
# - S-045: dataloader path in upstream smoke suite
# - S-046: forward path
# - S-047: backward path
# - S-048: checkpoint save/load path
# The concrete upstream cases are selected by torchtitan's integration suite
# under tests/integration_tests/.
run_upstream_smoke() {
    log_info "Running torchtitan upstream integration tests..."
    mkdir -p "$REPORT_DIR"

    # Ensure torchtitan_npu is installed
    if ! python3 -c "import torchtitan_npu" 2>/dev/null; then
        python3 -m pip install -e .
    fi

    # Check if torchtitan source exists
    if [[ ! -d "$TITAN_DIR" ]]; then
        log_info "Cloning torchtitan source..."
        mkdir -p third_party
        git clone --branch $TITAN_VERSION --depth 1 \
            https://gitcode.com/GitHub_Trending/to/torchtitan.git $TITAN_DIR
    fi

    local smoke_log="${REPORT_DIR}/upstream_smoke.log"
    local upstream_output_dir="${REPORT_DIR}/upstream_integration_output"
    local start_time=$(date +%s)
    local titan_test_dir="${TITAN_DIR}/tests/integration_tests"
    local conftest_file="${titan_test_dir}/conftest.py"
    local saved_pythonpath="$PYTHONPATH"

    if [[ ! -d "$titan_test_dir" ]]; then
        log_error "Torchtitan integration test directory not found: $titan_test_dir"
        return 1
    fi

    cd "$TITAN_DIR"

    rm -rf "$upstream_output_dir"
    mkdir -p "$upstream_output_dir"

    # Ensure torchtitan_npu patches are applied before upstream integration cases import torchtitan modules.
    cat > "$conftest_file" << 'EOF'
# Auto-generated conftest for torchtitan-npu upstream integration testing
def pytest_configure(config):
    import torchtitan_npu  # noqa: F401
EOF

    export PYTHONPATH="${TITAN_DIR}:${PROJECT_ROOT}:${PYTHONPATH}"

    # Run upstream integration tests with NPU patches applied.
    local cmd=(
        python3 -m tests.integration_tests.run_tests
        "$upstream_output_dir"
        --test_suite "$UPSTREAM_TEST_SUITE"
        --test_name "$UPSTREAM_TEST_NAME"
        --ngpu "$NGPU"
    )

    set +e
    "${cmd[@]}" 2>&1 | tee "$smoke_log"
    local exit_code=${PIPESTATUS[0]}
    set -e

    cd "$PROJECT_ROOT"
    rm -f "$conftest_file"
    export PYTHONPATH="$saved_pythonpath"

    local end_time=$(date +%s)
    local duration=$((end_time - start_time))
    log_info "Upstream integration test duration: ${duration}s"

    if [[ $exit_code -eq 0 ]]; then
        log_info "Upstream integration tests passed!"
    else
        log_error "Upstream smoke failed; stopping smoke pipeline."
        log_error "Upstream integration tests failed (exit_code=$exit_code)"
        return $exit_code
    fi
}

# Run extended local smoke suites
run_extended_smoke() {
    log_info "Running extended smoke suites..."
    mkdir -p "$REPORT_DIR"

    local smoke_targets=(
        "tests/smoke_tests/features/"
        "tests/smoke_tests/model_parallel/"
    )
    local available_targets=()
    local target
    for target in "${smoke_targets[@]}"; do
        if [[ -d "$target" ]]; then
            available_targets+=("$target")
        fi
    done

    if [[ ${#available_targets[@]} -eq 0 ]]; then
        log_info "No extended smoke directories found, skipping..."
        return 0
    fi

    local smoke_log="${REPORT_DIR}/extended_smoke.log"
    local pytest_args=(-v --tb=short -m "not nightly")
    pytest_args+=($(build_pytest_report_args "extended_smoke_report"))

    set +e
    python3 -m pytest "${available_targets[@]}" "${pytest_args[@]}" 2>&1 | tee "$smoke_log"
    local exit_code=${PIPESTATUS[0]}
    set -e

    if [[ $exit_code -eq 0 ]]; then
        log_info "Extended smoke suites passed!"
    else
        log_error "Extended smoke failed; stopping smoke pipeline."
        log_error "Extended smoke suites failed (exit_code=$exit_code)"
        return $exit_code
    fi
}

# Core smoke keeps the original semantics of `build.sh -s`:
# run a tiny training configuration through the real training entry.
run_core_smoke() {
    log_info "Running core smoke (small-model training path)..."

    cd "$PROJECT_ROOT"
    mkdir -p "$REPORT_DIR"

    local smoke_log="${REPORT_DIR}/smoke_test.log"
    local start_time=$(date +%s)

    echo " Verifying torchtitan "
    python -c "import torchtitan; print('torchtitan ok')"

    echo " Done "

    cd "$PROJECT_ROOT"
    chmod +x ./run_train.sh

    log_info "Prepared for entering"

    set +e 
    timeout $TIMEOUT_SECONDS bash -c "
        export NGPU=$NGPU
        export CONFIG_FILE="${SMOKE_CONFIG}"
        ./run_train.sh
    " 2>&1 | tee "$smoke_log"
    local exit_code=${PIPESTATUS[0]}
    set -e

    local end_time=$(date +%s)
    local duration=$((end_time - start_time))
    log_info "duration smoke time: ${duration}s"
    if ! analyse_smoke_result "$smoke_log" "$exit_code"; then
        log_error "Core smoke failed; stopping smoke pipeline."
        return 1
    fi
}

# Main smoke test entry
do_smoke_test() {
    local run_core=true
    local run_extended=true
    local run_upstream=false
    local smoke_stages=()

    python3 -m pip install pytest pytest-html pytest-cov pytest-mock

    if [[ "$ONLY_CORE_SMOKE" == "true" || "$ONLY_EXTENDED_SMOKE" == "true" || "$ONLY_UPSTREAM_SMOKE" == "true" ]]; then
        run_core=false
        run_extended=false
        run_upstream=false
        [[ "$ONLY_CORE_SMOKE" == "true" ]] && run_core=true
        [[ "$ONLY_EXTENDED_SMOKE" == "true" ]] && run_extended=true
        [[ "$ONLY_UPSTREAM_SMOKE" == "true" ]] && run_upstream=true
    fi

    [[ "$run_core" == "true" ]] && smoke_stages+=("run_core_smoke")
    [[ "$run_extended" == "true" ]] && smoke_stages+=("run_extended_smoke")
    [[ "$run_upstream" == "true" ]] && smoke_stages+=("run_upstream_smoke")

    local stage_runner
    for stage_runner in "${smoke_stages[@]}"; do
        if ! "$stage_runner"; then
            write_report_index
            log_error "smoke test failed"
            exit 1
        fi
    done

    write_report_index
    log_info "smoke test pass"
}

analyse_smoke_result() {
    local log_file="$1"
    local exit_code="$2"

    log_info "Analysing result of smoke test"
    local has_error=false

    if [[ "$exit_code" -eq 124 ]]; then
        log_error "Timeout!"
        has_error=true
    fi

    if grep -qiE "error|exception|traceback" "$log_file" 2>/dev/null; then
        if grep -qiE "NPU error|RuntimeError|OOM|OutOfMemory" "$log_file"; then
            log_error "error detected during running"
            grep -iE "NPU error|RuntimeError|OOM|OutOfMemory" "$log_file" | head -10
            has_error=true
        fi
    fi

    if echo "$clean_log" | grep -qiE "loss[^:]*:[^0-9]*(nan|inf)" \
    || echo "$clean_log" | grep -qiE "(nan|inf).*loss"; then
        log_error "loss error (NAN/Inf)"
        has_error=true
    fi

    local complete_steps=$(grep -oP "step[:\s]*\K\d+" "$log_file" 2>/dev/null | tail -1 || echo "0")
    if [[ "$completed_steps" -ge "$SMOKE_STEPS" ]]; then
        log_info "Completed $complete_steps steps"
    elif [[ "$completed_steps" -gt 0 ]]; then
        log_error "Only finished $complete_steps/$SMOKE_STEPS steps"
    else
        log_error "No output steps detected"
    fi

    if [[ "$has_error" == "true" ]] || [[ "$exit_code" -ne 0 ]]; then
        return 1
    fi

    return 0
}

main() {
    parse_args "$@"

    log_info "Torchtitan-npu build"

    if [[ "$DO_BUILD" == "true" ]] || [[ "$DO_UNIT_TEST" == "true" ]] || [[ "$DO_SMOKE_TEST" == "true" ]]; then 
        check_environment
    fi

    if [[ "$DO_CLEAN" == "true" ]]; then
        do_clean
    fi

    if [[ "$DO_BUILD" == "true" ]]; then
        do_build
    fi

    if [[ "$DO_INSTALL" == "true" ]]; then
        do_install
    fi

    if [[ "$DO_UNIT_TEST" == "true" ]]; then
        do_unit_test
    fi

    if [[ "$DO_SMOKE_TEST" == "true" ]]; then
        do_smoke_test
    fi
}

main "$@"
