[job]
dump_folder = "./outputs"
description = "DeepSeek-V3.2 671B model training"
print_config = false
custom_config_module = "torchtitan_npu.config.custom_config"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_ranks = [0]
profile_step_start = 5
profile_step_end = 6
profile_record_shapes = true
profile_with_memory = false
profile_with_stack = false

# ignored them when profile_step_start and profile_step_end are set
# profile_freq = 10
# profiler_active = 1
# profiler_warmup = 1

enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
disable_color_printing = false
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = false

[model]
name = "deepseek_v32"
flavor = "debugmodel"
hf_assets_path = "./assets/hf/DeepSeek-V3.2"
converters = ["npu_dsa", "npu_rms_norm", "npu_permute", "npu_gmm", "npu_rope"]

[optimizer]
name = "AdamW"
lr = 2.2e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 4  # lr scheduler warm up, normally 20% of the train steps
decay_ratio = 0.8  # lr scheduler decay ratio, 80% of the train steps
decay_type = "cosine"
min_lr_factor = 0.1

[training]
local_batch_size = 2
seq_len = 2048
max_norm = 1.0  # grad norm clipping
steps = 20
dataset = "c4_test"

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
fsdp_reshard_after_forward = "default" # default / never / always
tensor_parallel_degree = 1
enable_async_tensor_parallel = false
pipeline_parallel_degree = 1
pipeline_parallel_schedule = "Interleaved1F1B"
expert_parallel_degree = 1
expert_tensor_parallel_degree = 1
context_parallel_degree = 1
enable_custom_context_parallel = true


[checkpoint]
enable = false
folder = "path/to/checkpoint"
# initial_load_model_only = true
# initial_load_in_hf = true
# initial_load_path = "/path/to/hf-weight"
interval = 500
last_save_model_only = false
export_dtype = "float32"
async_mode = "disabled"  # ["disabled", "async", "async_with_pinned_mem]"

[activation_checkpoint]
mode = "full"  # ["none", "selective", "full"]
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[compile]
enable = false
components = ["loss"] # ["model", "loss"]

[quantize.linear.float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output", "router.gate"]

[quantize.grouped_mm.float8]
fqns = ["experts"]

[comm]
trace_buf_size = 0
